In [11]:
#Write a function to compute 5/0 and use try/except to catch the exceptions.
try:
    x=5
    y=0
    z=x/y
except:
    print("error when dividing by zero")
else:
    print(z)

error when dividing by zero


In [12]:
#Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
sub=['Americans', "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]
x=[[sb +" "+vr+" "+ob] for sb in sub for vr in verb for ob in obj]
for i in x:
    print(i[0])

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [13]:
#Write a function so that the columns of the output matrix are powers of the input vector.
import numpy as np
def matrix(vect):
    x = np.array(vect)
    N=len(x)
    y = np.array([x**i for i in range(N)])
    return(y.T)

In [14]:
vect =[1,2,3,4,5]
print(matrix(vect))

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
